/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.ListModel;

/**
 *
 * @author Daniel Collaguazo Malla
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        cajero1 = new javax.swing.JLabel();
        cajero2 = new javax.swing.JLabel();
        cajero3 = new javax.swing.JLabel();
        persona1 = new javax.swing.JLabel();
        persona2 = new javax.swing.JLabel();
        persona4 = new javax.swing.JLabel();
        persona3 = new javax.swing.JLabel();
        persona5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        iniciar = new javax.swing.JButton();
        parar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCajero3 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        listCajero1 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        listCajero2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajero1.setBackground(new java.awt.Color(204, 0, 0));
        cajero1.setForeground(new java.awt.Color(0, 0, 0));
        cajero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cajero.jpg"))); // NOI18N
        cajero1.setMaximumSize(new java.awt.Dimension(34, 34));
        cajero1.setMinimumSize(new java.awt.Dimension(34, 34));
        cajero1.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(cajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 125, 127));

        cajero2.setBackground(new java.awt.Color(204, 0, 0));
        cajero2.setForeground(new java.awt.Color(0, 0, 0));
        cajero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cajero.jpg"))); // NOI18N
        cajero2.setMaximumSize(new java.awt.Dimension(34, 34));
        cajero2.setMinimumSize(new java.awt.Dimension(34, 34));
        cajero2.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(cajero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 125, 127));

        cajero3.setBackground(new java.awt.Color(204, 0, 0));
        cajero3.setForeground(new java.awt.Color(0, 0, 0));
        cajero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cajero.jpg"))); // NOI18N
        cajero3.setMaximumSize(new java.awt.Dimension(34, 34));
        cajero3.setMinimumSize(new java.awt.Dimension(34, 34));
        cajero3.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(cajero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 125, 127));

        persona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Azul.jpg"))); // NOI18N
        getContentPane().add(persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 551, -1, -1));

        persona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Naranja.jpg"))); // NOI18N
        getContentPane().add(persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 551, -1, -1));

        persona4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Rosa.jpg"))); // NOI18N
        getContentPane().add(persona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 551, -1, -1));

        persona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Rojo.jpg"))); // NOI18N
        getContentPane().add(persona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 551, -1, -1));

        persona5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verde.jpg"))); // NOI18N
        getContentPane().add(persona5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 551, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 840, 170));

        iniciar.setText("Iniciar");

        parar.setText("Parar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 668, -1, -1));

        jLabel1.setFont(new java.awt.Font("Raleway Black", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 264, 34));

        listCajero3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cliente O:", "Cuenta:", "Monto:", "Cliente D:", "Estado:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCajero3.setToolTipText("");
        jScrollPane4.setViewportView(listCajero3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 150, 100));

        listCajero1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cliente O:", "Cuenta:", "Monto:", "Cliente D:", "Estado:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCajero1.setToolTipText("");
        jScrollPane6.setViewportView(listCajero1);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 150, 100));

        listCajero2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cliente O:", "Cuenta:", "Monto:", "Cliente D:", "Estado:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCajero2.setToolTipText("");
        jScrollPane7.setViewportView(listCajero2);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 150, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }
    
    public void listenerBotonIniciar(ActionListener listener){
        iniciar.addActionListener(listener);
    }

    public JLabel getCajero1() {
        return cajero1;
    }

    public JLabel getCajero2() {
        return cajero2;
    }

    public JLabel getCajero3() {
        return cajero3;
    }

    public JLabel getPersona1() {
        return persona1;
    }

    public JLabel getPersona2() {
        return persona2;
    }

    public JLabel getPersona3() {
        return persona3;
    }

    public JLabel getPersona4() {
        return persona4;
    }

    public JLabel getPersona5() {
        return persona5;
    }
    public void setmodelListCajero1(ListModel m){
        listCajero1.setModel(m);
    }
    public void setmodelListCajero2(ListModel m){
        listCajero2.setModel(m);
    }
    public void setmodelListCajero3(ListModel m){
        listCajero3.setModel(m);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cajero1;
    private javax.swing.JLabel cajero2;
    private javax.swing.JLabel cajero3;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listCajero1;
    private javax.swing.JList<String> listCajero2;
    private javax.swing.JList<String> listCajero3;
    private javax.swing.JButton parar;
    private javax.swing.JLabel persona1;
    private javax.swing.JLabel persona2;
    private javax.swing.JLabel persona3;
    private javax.swing.JLabel persona4;
    private javax.swing.JLabel persona5;
    // End of variables declaration//GEN-END:variables
}
