/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Daniel Collaguazo Malla
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        cajero1 = new javax.swing.JLabel();
        cajero2 = new javax.swing.JLabel();
        cajero3 = new javax.swing.JLabel();
        persona1 = new javax.swing.JLabel();
        persona2 = new javax.swing.JLabel();
        persona4 = new javax.swing.JLabel();
        persona3 = new javax.swing.JLabel();
        persona5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        iniciar = new javax.swing.JButton();
        parar = new javax.swing.JButton();
        txtCajero = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campo = new javax.swing.JScrollPane();
        campoText3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoText1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        campoText2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajero1.setBackground(new java.awt.Color(204, 0, 0));
        cajero1.setForeground(new java.awt.Color(0, 0, 0));
        cajero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cajero.jpg"))); // NOI18N
        cajero1.setMaximumSize(new java.awt.Dimension(34, 34));
        cajero1.setMinimumSize(new java.awt.Dimension(34, 34));
        cajero1.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(cajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 125, 127));

        cajero2.setBackground(new java.awt.Color(204, 0, 0));
        cajero2.setForeground(new java.awt.Color(0, 0, 0));
        cajero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cajero.jpg"))); // NOI18N
        cajero2.setMaximumSize(new java.awt.Dimension(34, 34));
        cajero2.setMinimumSize(new java.awt.Dimension(34, 34));
        cajero2.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(cajero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 125, 127));

        cajero3.setBackground(new java.awt.Color(204, 0, 0));
        cajero3.setForeground(new java.awt.Color(0, 0, 0));
        cajero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cajero.jpg"))); // NOI18N
        cajero3.setMaximumSize(new java.awt.Dimension(34, 34));
        cajero3.setMinimumSize(new java.awt.Dimension(34, 34));
        cajero3.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(cajero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 125, 127));

        persona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Azul.jpg"))); // NOI18N
        getContentPane().add(persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        persona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Naranja.jpg"))); // NOI18N
        getContentPane().add(persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        persona4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Rosa.jpg"))); // NOI18N
        getContentPane().add(persona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        persona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Rojo.jpg"))); // NOI18N
        getContentPane().add(persona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        persona5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verde.jpg"))); // NOI18N
        getContentPane().add(persona5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 840, 170));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciar.setText("Iniciar");
        jPanel1.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 40));

        parar.setText("Parar");
        jPanel1.add(parar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 40));

        txtCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, -1));
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, -1));

        jLabel2.setText("Clientes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel3.setText("Cajeros:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, -1, 210));

        jLabel1.setFont(new java.awt.Font("Raleway Black", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 264, 34));

        campoText3.setColumns(20);
        campoText3.setRows(5);
        campo.setViewportView(campoText3);

        getContentPane().add(campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 160, 110));

        campoText1.setColumns(20);
        campoText1.setRows(5);
        jScrollPane3.setViewportView(campoText1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 160, 110));

        campoText2.setColumns(20);
        campoText2.setRows(5);
        jScrollPane5.setViewportView(campoText2);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 160, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }
    
    public void listenerBotonIniciar(ActionListener listener){
        iniciar.addActionListener(listener);
    }
    public void listenerBotonParar(ActionListener listener){
        parar.addActionListener(listener);
    }

    public JLabel getCajero1() {
        return cajero1;
    }

    public JLabel getCajero2() {
        return cajero2;
    }

    public JLabel getCajero3() {
        return cajero3;
    }

    public JLabel getPersona1() {
        return persona1;
    }

    public JLabel getPersona2() {
        return persona2;
    }

    public JLabel getPersona3() {
        return persona3;
    }

    public JLabel getPersona4() {
        return persona4;
    }

    public JLabel getPersona5() {
        return persona5;
    }

    public JTextField getTxtCajero() {
        return txtCajero;
    }

    public void setTxtCajero(JTextField txtCajero) {
        this.txtCajero = txtCajero;
    }

    public JTextField getTxtCliente() {
        return txtCliente;
    }

    public void setTxtCliente(JTextField txtCliente) {
        this.txtCliente = txtCliente;
    }
    
    public JTextArea getCampoText1() {
        return campoText1;
    }

    public JTextArea getCampoText2() {
        return campoText2;
    }

    public JTextArea getCampoText3() {
        return campoText3;
    }
    
    public void setModelTable(TableModel model){
    tabla.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cajero1;
    private javax.swing.JLabel cajero2;
    private javax.swing.JLabel cajero3;
    private javax.swing.JScrollPane campo;
    private javax.swing.JTextArea campoText1;
    private javax.swing.JTextArea campoText2;
    private javax.swing.JTextArea campoText3;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton parar;
    private javax.swing.JLabel persona1;
    private javax.swing.JLabel persona2;
    private javax.swing.JLabel persona3;
    private javax.swing.JLabel persona4;
    private javax.swing.JLabel persona5;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCajero;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
